### ISSUE TITLE
[FEATURE] Todolist service java ms

### ISSUE THREAD

**Issue by MarcoFierimonte** [mmonkeyteam/a-new-todos#14]
# Description

As a developer I want to create the initial java project, so that it can be used to next developments.

## Things to do 

- [x] Create Gradle project
- [x] Study and configure Travis
- [ ] Connect to database
- [ ] Expose first REST endpoint

**Comment by MarcoFierimonte** [comment]
Added initial travis.yml file. Deepen the topic and add jacoco test coverage.

**Comment by MarcoFierimonte** [comment]
Creating Spring Boot OpenAPI Rest service.
**Starting poing:** https://dzone.com/articles/spring-boot-2-restful-api-documentation-with-swagg
